# /auth/register
#注册用户的API测试
POST /auth/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
    "username": "xiedan",
    "phoneNumber": "13912345679",
    "password": "123456"
    //"verificationCode": "251038"
}

# /auth/send-verificationcode
# 测试发送验证码的API，但并不是真正发送，api还没调用
POST /auth/send-verificationcode HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
    "phone": "13912345678"
}

POST /auth/send-verificationcode HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
    "phone": "14912345679"
}

# /auth/send-verificationcode
# 测试手机号不规范的API调用情况
POST /auth/send-verificationcode HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
    "phone": "14912345679"
}



POST /auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
    "username": "Milky",
    "password": "123456"
}

GET /plans HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache



POST /plans HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
  "title": "清明节回家",
  "startTime": "2025-06-18T13:03",
  "endTime": "2026-03-12T19:12",
  "isCompleted": false,
  "description": "清明节开车回家，希望晚上上机可以提前结束"
}

PUT /plans/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQ2NjE1MjgzLCJleHAiOjE3NDY2NTEyODN9.EkGUPpZPLn6hgQeH5ElsoNSplE9zFBd89yzvpxggW7A
Host:localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
  "title": "学习vue4",
  "startTime": "2025-06-18T13:03:27",
  "endTime": "2026-03-12T19:12:13",
  "isCompleted": true,
  "description": "vue4知识点太多了，要好好学习，多敲代码。"
}


DELETE /plans/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQ2NjE1MjgzLCJleHAiOjE3NDY2NTEyODN9.EkGUPpZPLn6hgQeH5ElsoNSplE9zFBd89yzvpxggW7A
Host:localhost:8080
Content-Type: application/json
Cache-Control: no-cache


GET /todos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host:localhost:8080
Content-Type: application/json
Cache-Control: no-cache

POST /todos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
  "title": "完成后端与数据库的增删查改",
  "priority": "high",
  "deadline": "2024-03-20T18:00",
  "description": "需要与前端进行对接"
}

PUT /todos/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQ2NjE1MjgzLCJleHAiOjE3NDY2NTEyODN9.EkGUPpZPLn6hgQeH5ElsoNSplE9zFBd89yzvpxggW7A
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
  "title": "清明节回家",
  "priority": "medium",
  "isCompleted": false,
  "updatedAt": "2019-08-24T14:15:22.123Z",
  "deadline": "2019-08-24T14:15:22.123Z",
  "reminderTime": "2019-08-24T14:15:21.123Z",
  "description": "清明节开车回家"
}


DELETE /todos/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache


GET /plans/processes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjgwMDM1LCJleHAiOjE3NDM3MTYwMzV9.81S-Mzq2hkURohjHbGamuoy9zVq5fo_iGI_zPijLuP0
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache


POST  /plans/3/processes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
  "content": "SpringBoot的各种特性——全自动化的感觉",
  "completedTime": "2025-02-03T15:30"
}


PUT /plans/1/processes/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjQzMDIyLCJleHAiOjE3NDM2NzkwMjJ9.VJcm69mgx8vH_FdAVA1-Ps6ts5ZeSXjxBD8yOQAA4VU
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache

{
  "content": "看B站视频学习了vue4的计算属性",
  "completedTime": "2019-08-24T14:15:22.123Z"
}

DELETE /plans/10/processes/13 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQzNjgwMDM1LCJleHAiOjE3NDM3MTYwMzV9.81S-Mzq2hkURohjHbGamuoy9zVq5fo_iGI_zPijLuP0
Host: localhost:8080
Content-Type: application/json
Cache-Control: no-cache


POST /Ctable HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzQ2NTQxNjA5LCJleHAiOjE3NDY1Nzc2MDl9.ohHDgFoxJ38TQPR6iymgAsCcfDmpn5EJRM2DoRvFViM
Host: localhost:8080
Content-Type: multipart/form-data; charset=UTF-8; boundary=----MyBoundary

-----MyBoundary
Content-Disposition: form-data; name="file"; filename="谢丹(2024-2025-2)课表.pdf"
Content-Type: application/pdf

< C://javaProject//Time-Management//time-management//谢丹(2024-2025-2)课表.pdf
-----MyBoundary--